//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ReverseStringSoap")]
    public interface ReverseStringSoap {
        
        // CODEGEN: Generating message contract since the wrapper name (ReverseString) of message ReverseString does not match the default value (GetReverseString)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReverseString", ReplyAction="*")]
        Api.ServiceReference1.ReverseString1 GetReverseString(Api.ServiceReference1.ReverseString request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReverseString", ReplyAction="*")]
        System.Threading.Tasks.Task<Api.ServiceReference1.ReverseString1> GetReverseStringAsync(Api.ServiceReference1.ReverseString request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseString", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseString {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string Sentence;
        
        public ReverseString() {
        }
        
        public ReverseString(string Sentence) {
            this.Sentence = Sentence;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReverseStringResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ReverseString1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string ReverseStringResult;
        
        public ReverseString1() {
        }
        
        public ReverseString1(string ReverseStringResult) {
            this.ReverseStringResult = ReverseStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReverseStringSoapChannel : Api.ServiceReference1.ReverseStringSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReverseStringSoapClient : System.ServiceModel.ClientBase<Api.ServiceReference1.ReverseStringSoap>, Api.ServiceReference1.ReverseStringSoap {
        
        public ReverseStringSoapClient() {
        }
        
        public ReverseStringSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReverseStringSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReverseStringSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReverseStringSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Api.ServiceReference1.ReverseString1 Api.ServiceReference1.ReverseStringSoap.GetReverseString(Api.ServiceReference1.ReverseString request) {
            return base.Channel.GetReverseString(request);
        }
        
        public string GetReverseString(string Sentence) {
            Api.ServiceReference1.ReverseString inValue = new Api.ServiceReference1.ReverseString();
            inValue.Sentence = Sentence;
            Api.ServiceReference1.ReverseString1 retVal = ((Api.ServiceReference1.ReverseStringSoap)(this)).GetReverseString(inValue);
            return retVal.ReverseStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Api.ServiceReference1.ReverseString1> Api.ServiceReference1.ReverseStringSoap.GetReverseStringAsync(Api.ServiceReference1.ReverseString request) {
            return base.Channel.GetReverseStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<Api.ServiceReference1.ReverseString1> GetReverseStringAsync(string Sentence) {
            Api.ServiceReference1.ReverseString inValue = new Api.ServiceReference1.ReverseString();
            inValue.Sentence = Sentence;
            return ((Api.ServiceReference1.ReverseStringSoap)(this)).GetReverseStringAsync(inValue);
        }
    }
}
